// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDSuuFS5AB8AbmzJkHf0yGYyH0uFpM1GQ',
    appId: '1:233610521690:web:aa0919e364ec8455c33c63',
    messagingSenderId: '233610521690',
    projectId: 'e-survey-3b1f8',
    authDomain: 'e-survey-3b1f8.firebaseapp.com',
    storageBucket: 'e-survey-3b1f8.appspot.com',
    measurementId: 'G-68YVC6VKYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUUJAp2pc32SPJZnYrx5E3Za2KC2dnvkQ',
    appId: '1:233610521690:android:953b4451d7521414c33c63',
    messagingSenderId: '233610521690',
    projectId: 'e-survey-3b1f8',
    storageBucket: 'e-survey-3b1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM7Yp8ut1OJc0qKZEAS43TMSRb6gM0MJs',
    appId: '1:233610521690:ios:4626c1256c925c51c33c63',
    messagingSenderId: '233610521690',
    projectId: 'e-survey-3b1f8',
    storageBucket: 'e-survey-3b1f8.appspot.com',
    iosClientId: '233610521690-d2piu6sk6b9ensidpgrt97g1iqeojtbm.apps.googleusercontent.com',
    iosBundleId: 'com.claims.eSurvey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM7Yp8ut1OJc0qKZEAS43TMSRb6gM0MJs',
    appId: '1:233610521690:ios:cdbce7b312a40505c33c63',
    messagingSenderId: '233610521690',
    projectId: 'e-survey-3b1f8',
    storageBucket: 'e-survey-3b1f8.appspot.com',
    iosClientId: '233610521690-2pe38snilrjove3t2v7sr99ib5rvs0lq.apps.googleusercontent.com',
    iosBundleId: 'com.claims.eSurvey.RunnerTests',
  );
}
